### ISSUE TITLE
convert-pth-to-ggml.py expects 2 parts for ALPACA-LORA-13B, but it has only one

### ISSUE THREAD

**Issue by stduhpf** [PotatoSpudowski/fastLLaMa#57]
the `export-from-huggingface.py` scripts only generates one checkpoint file (`consolidated.00.pth`) for ALPACA-LORA-13B, but when I then run `python3 ./scripts/convert-pth-to-ggml.py models/ALPACA-LORA-13B 1 0`
I get the following output: 
```
{'dim': 5120, 'multiple_of': 256, 'n_heads': 40, 'n_layers': 40, 'norm_eps': 1e-06, 'vocab_size': -1}
Namespace(dir_model='models/ALPACA-LORA-13B', ftype=1, vocab_only=0)
n_parts = 2

Processing part 1 of 2

[...]
Processing part 2 of 2

Traceback (most recent call last):
  File "./scripts/convert-pth-to-ggml.py", line 274, in <module>
    main()
  File "./scripts/convert-pth-to-ggml.py", line 267, in main
    model = torch.load(fname_model, map_location="cpu")
[...]
FileNotFoundError: [Errno 2] No such file or directory: 'models/ALPACA-LORA-13B/consolidated.01.pth'
```
The old version of this script was handling this correctly.

**Comment by stduhpf** [comment]
Also I get this error when I try to run it:
```
[Info]: Func('Model') loading model(='ALPACA-LORA-13B') from ./models/ALPACA-LORA-13B/alpaca-lora-q4_0.bin - please wait ...
[Info]: Func('KVCacheBuffer::init') kv self size  =  512.00 MB
[Error]: Func('Model') invalid model file ./models/ALPACA-LORA-13B/alpaca-lora-q4_0.bin (bad magic)
[Error]: Func('FastLlama::Params::build') Unable to load model
Traceback (most recent call last):
  File "examples/python/example-alpaca.py", line 11, in <module>
    model = Model(
  File "examples/python/build/fastllama.py", line 208, in __init__
    raise RuntimeError("Unable to load model")
RuntimeError: Unable to load model
Exception ignored in: <function Model.__del__ at 0x7f4e2d3cb310>
Traceback (most recent call last):
  File "examples/python/build/fastllama.py", line 404, in __del__
    signal.signal(signal.SIGINT, signal.SIG_DFL)
  File "~/miniconda3/envs/fastllama/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by PotatoSpudowski** [comment]
Ah yes, 
Good catch. I was trying to move away from my hacky implementation. In our old method, for large models, creating just one file was not a good idea because of high memory usage during conversion and quantization steps. 

I wanted to add a way to split the models into smaller parts during the exporting part. 
Please give me some time I will get it done by tonight.

**Comment by PotatoSpudowski** [comment]
Meanwhile you can try the sync_llama branch for now. 
All ggml models exported to huggingface work now. Been testing Vicuna and Alpaca 7B and 13B

**Comment by PotatoSpudowski** [comment]
This should be fixed in the new PR, can you please check?

**Comment by stduhpf** [comment]
Fixed!
