### ISSUE TITLE
Bad Magic error

### ISSUE THREAD

**Issue by Th3F0x-code** [PotatoSpudowski/fastLLaMa#58]
when I try to load the template the error below comes up

```
[Info]: Func('Model') loading model(='LLAMA-7B') from ./models/7B/ggml-model-q4_0.bin - please wait ...
[Info]: Func('KVCacheBuffer::init') kv self size  =  512.00 MB
[Error]: Func('Model') invalid model file ./models/7B/ggml-model-q4_0.bin (bad magic)
[Error]: Func('FastLlama::Params::build') Unable to load model
```

**Comment by PotatoSpudowski** [comment]
Hi, 
Can you please check the latest main branch?
@amitsingh19975 implemented a fix!

**Comment by Th3F0x-code** [comment]
now it works, thank you :D

**Comment by Th3F0x-code** [comment]
now there is this problem

```
Exception ignored in: <function Model.__del__ at 0x1053cdd30>
Traceback (most recent call last):
  File "/Volumes/SSD/fastLLaMa/examples/python/build/fastllama.py", line 404, in __del__
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by amitsingh19975** [comment]
It's a python issue (maybe I'm wrong). Could you send me the whole command that you ran?

**Comment by Th3F0x-code** [comment]
this is the command:
`(.venv) alessio@MacBook-Pro-di-Alessio fastLLaMa % python ./examples/python/example.py`

and this is my python version:
`Python 3.9.6`

**Comment by PotatoSpudowski** [comment]
Was able to recreate this in python 3.9 as well. 

Quick fix is comment the stop words, it was getting killed prematurely. I will push the change. Good catch!

`res = model.generate(
    num_tokens=100, 
    top_p=0.95, #top p sampling (Optional)
    temp=0.8, #temperature (Optional)
    repeat_penalty=1.0, #repetition penalty (Optional)
    streaming_fn=stream_token, #streaming function
    # stop_words=[] #stop generation when this word is encountered (Optional)
    )`

**Comment by PotatoSpudowski** [comment]
Can use the latest branch now! 
Alternatively you can try changing the stop word as well! 

Hope this fixed the issue :)
